### ISSUE TITLE
Missing field in getFills

### ISSUE THREAD

**Issue by MaroonMike** [benfranke/gdax-php#4]
Message: Encountered unknown fields in response: {"usd_volume":"8116.0064466000000000"}

Filename: Traits/ResponseTypeTrait.php

Line Number: 61

Backtrace:

File: /home/surepoint/public_html/application/vendor/benfranke/gdax-php/src/Traits/ResponseTypeTrait.php
Line: 61
Function: trigger_error

File: /home/surepoint/public_html/application/vendor/benfranke/gdax-php/src/Types/Response/ResponseContainer.php
Line: 45
Function: initFromArray

File: /home/surepoint/public_html/application/vendor/benfranke/gdax-php/src/Clients/PublicClient.php
Line: 80
Function: mapResponseToType

File: /home/surepoint/public_html/application/vendor/benfranke/gdax-php/src/Clients/AuthenticatedClient.php
Line: 229
Function: get

Function: getFills

**Comment by benfranke** [comment]
Should be fixed in release 0.0.6.
